@Library('dot-shared-lib@v3.3.2') _
pipeline {

    options {
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '15'))
        timeout(time: 2, unit: 'HOURS')
        timestamps()
    }

    environment {
        PROJECT_NAME = 'T1224-OneOPS'
        PROJECT_TEAM = 'myteam'
        REGISTRY = 'registry.app.corpintra.net'
        SONAR_CREDENTIALS = 'pid5309-sonar-token'
        SONAR_HOST = 'https://dfscto-sonar.dot.i.mercedes-benz.com'
        AUTH_FILE = credentials('FS_PROD_CI_AUTHFILE')
        API_VERSION = credentials('API_VERSION')
        SFDX_DISABLE_DNS_CHECK = true 
    }

    agent any

    stages {
        stage('Set Up Environment') {
            steps {
                setEnv(enableStatistics: false)
            }
        }
        stage('Create Scratch Org Pool') {
            agent {
                docker {
                alwaysPull true
                image 'registry.app.corpintra.net/dmo/docker-salesforce:7.188.2'
                args '-u root'
                reuseNode true
                }
            }
            steps {
                sh "chmod +x .deployment/scripts/*.sh"
                sh ".deployment/scripts/configSetAPIVersion.sh $API_VERSION"
                sh ".deployment/scripts/authenticationSFDXURL.sh FS_PROD $AUTH_FILE SetAsDefaultDEVHUB"
                sh "sfdx sfpowerscripts:orchestrator:prepare -f config/ScratchOrg-Pooling/MB-CI-SOPool-config.json --targetdevhubusername=FS_PROD"
            }
        }
    }

    post {
        always {
            cleanWs()
            dir("${env.WORKSPACE}@tmp") {
                deleteDir()
            }
        }
    }

}