@Library('dot-shared-lib@master') _
pipeline {

    options {
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '15'))
        timeout(time: 2, unit: 'HOURS')
        timestamps()
    }

    environment {
        PROJECT_NAME = 'T1224-OneOPS'
        PROJECT_TEAM = 'myteam'
        REGISTRY = 'registry.app.corpintra.net'
        SONAR_CREDENTIALS = 'pid5309-sonar-token'
        SONAR_HOST = 'https://dfscto-sonar.dot.i.mercedes-benz.com'
        AUTH_FILE = credentials('FS_PROD_CI_AUTHFILE')
        API_VERSION = credentials('API_VERSION')
        CI_USER_PROD = credentials('CI_USER_PROD')
        CLIENTID_PROD = credentials('CLIENTID_PROD')
        URL_PROD = credentials('URL_PROD')
        INSTALLATIONKEY = credentials('INSTALLATION_KEY')
        SERVER_KEY_FILE = credentials('SF_SERVER_KEY')
        SFDX_DISABLE_DNS_CHECK = true 
    }

    agent any

    stages {
        stage('Set Up Environment') {
            steps {
                setEnv(enableStatistics: false)
            }
        }
        stage('Create and provide Scratch Org') {
            agent {
                docker {
                alwaysPull true
                image 'registry.app.corpintra.net/dmo/docker-salesforce:7.198.7'
                args '-u root'
                reuseNode true
                }
            }
            steps {
                    sh "chmod +x .deployment/scripts/*.sh"
                    sh ".deployment/scripts/configSetAPIVersion.sh $API_VERSION"
                    sh ".deployment/scripts/authentication.sh $CLIENTID_PROD $CI_USER_PROD FS_PROD $SERVER_KEY_FILE $URL_PROD SetAsDefaultDEVHUB"
                    sh ".deployment/scripts/scratchOrgCreate.sh FS_SO_ONEOPS_${env.BUILD_ID} FS_PROD true"
                    echo "Org created successfully. The upcoming step will provide you the link to access the Scratch Org:"
                    sh "sfdx org open -r"
            }
        }
    }
    
    post {
        always {
            cleanWs()
            dir("${env.WORKSPACE}@tmp") {
                deleteDir()
            }
        }
    }

}