name: 'CD: PROD - Deployment of Packages' 

on:
  workflow_dispatch:

env:
  INSTALLATIONKEY: ${{ secrets.INSTALLATIONKEY }}
  SFDX_DISABLE_DNS_CHECK: true 
  SALESFORCE_CLI_VERSION: ${{ vars.SALESFORCE_CLI_VERSION }}
  PACKAGEVERSIONID_COREDM: ${{ vars.PROMOTE_PACKAGE_VERSION_ID_CORE_DM }}
  PACKAGEVERSIONID_COREBL: ${{ vars.PROMOTE_PACKAGE_VERSION_ID_CORE_BL }}
  PACKAGEVERSIONID_COM_BATCH: ${{ vars.PROMOTE_PACKAGE_VERSION_ID_COM_BATCH }}
  PACKAGEVERSIONID_FSDM: ${{ vars.PROMOTE_PACKAGE_VERSION_ID_FS_DM }}
  PACKAGEVERSIONID_FSIVR: ${{ vars.PROMOTE_PACKAGE_VERSION_ID_FS_IVR }}
  PACKAGEVERSIONID_FSBL: ${{ vars.PROMOTE_PACKAGE_VERSION_ID_FS_BL }}
  PACKAGEVERSIONID_FS_CREDIT_DM: ${{ vars.PROMOTE_PACKAGE_VERSION_ID_FS_CREDIT_DM }}
  PACKAGEVERSIONID_FS_CREDIT_BL: ${{ vars.PROMOTE_PACKAGE_VERSION_ID_FS_CREDIT_BL }}
  RELEASE_VERSION: ${{ vars.RELEASE_VERSION }}
  TEAMS_NOTIFICATIONS_WEBHOOK: ${{ secrets.TEAMS_NOTIFICATIONS_WEBHOOK }}

jobs:
  deployToProduction:
    runs-on: [self-hosted, aks-gha-runners]
    environment: PROD

    steps:
      - uses: actions/checkout@v3

      - id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install Salesforce CLI
      - name: 'Install Salesforce CLI'
        run: |
          sudo npm install --global @salesforce/cli@${SALESFORCE_CLI_V2_VERSION} --ignore-scripts 
          sf --version

      # Store secret for DevHub / PROD
      - name: Populate auth file with DevHub_SFDX_URL secret
        run: echo ${{ secrets.DEVHUB_SFDX_URL}} > ./PROD_SFDX_URL.txt

      # Make scripts executable
      - name: Make scripts executable
        run: chmod +x .deployment/scripts/*.sh && chmod +x .deployment/scripts/orchastration_mb/*.sh

      # Authenticate to DevHub / PROD
      - name: Authenticate to DevHub / PROD
        run: .deployment/scripts/authenticationSFDXURL.sh FS_PROD PROD_SFDX_URL.txt SetAsDefaultDEVHUB

      # Run Package promotions
      - name: Run Package promotions
        run: |
          .deployment/scripts/packagePromote.sh FS_PROD $PACKAGEVERSIONID_COREDM
          .deployment/scripts/packagePromote.sh FS_PROD $PACKAGEVERSIONID_COM_BATCH
          .deployment/scripts/packagePromote.sh FS_PROD $PACKAGEVERSIONID_FSDM
          .deployment/scripts/packagePromote.sh FS_PROD $PACKAGEVERSIONID_FSIVR
          .deployment/scripts/packagePromote.sh FS_PROD $PACKAGEVERSIONID_FSBL
          .deployment/scripts/packagePromote.sh FS_PROD $PACKAGEVERSIONID_FS_CREDIT_DM
          .deployment/scripts/packagePromote.sh FS_PROD $PACKAGEVERSIONID_FS_CREDIT_BL
      
      # Run Deployment of CORE to PROD
      - name: Deployment of CORE to PROD
        run:  |
          .deployment/scripts/packageInstall.sh FS_PROD $PACKAGEVERSIONID_COREDM $INSTALLATIONKEY
          .deployment/scripts/orchastration_mb/post-deployment_core.sh FS_PROD RunLocalTests

      # Run Deployment of COM to PROD
      - name: Deployment of COM to PROD
        run:  |    
          .deployment/scripts/packageInstall.sh FS_PROD $PACKAGEVERSIONID_COM_BATCH $INSTALLATIONKEY
          .deployment/scripts/orchastration_mb/post-deployment_com.sh FS_PROD RunLocalTests

      # Run Deployment of FS to PROD
      - name: Deployment of FS to PROD
        id: FS_deployment
        run:  |       
          .deployment/scripts/orchastration_mb/pre-deployment_fs.sh FS_PROD RunLocalTests
          .deployment/scripts/packageInstall.sh FS_PROD $PACKAGEVERSIONID_FSDM $INSTALLATIONKEY
          .deployment/scripts/packageInstall.sh FS_PROD $PACKAGEVERSIONID_FSIVR $INSTALLATIONKEY
          .deployment/scripts/packageInstall.sh FS_PROD $PACKAGEVERSIONID_FSBL $INSTALLATIONKEY
          .deployment/scripts/packageInstall.sh FS_PROD $PACKAGEVERSIONID_FS_CREDIT_DM $INSTALLATIONKEY
          .deployment/scripts/packageInstall.sh FS_PROD $PACKAGEVERSIONID_FS_CREDIT_BL $INSTALLATIONKEY
          .deployment/scripts/orchastration_mb/post-deployment_fs.sh FS_PROD RunLocalTests
        #  .deployment/scripts/orchastration_mb/post-deployment_PROD.sh FS_PROD RunLocalTests - avoid overriting of quicklinks for the moment

      # Tab branch on deployment success
      - name: Tag main branch with Release
        if: steps.FS_deployment.outcome == 'success'
        run: |
          sudo apt-get install jq
          git config --global user.email "ci.user@mercedes-benz.com"
          git config --global user.name "CI User"
          .deployment/scripts/tag_PackageVersions.sh $RELEASE_VERSION FS_PROD
        
      # Send Teams notification
      - name: Post Deployment Status to Teams
        if: ${{ always() }}
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            curl -X POST -H "Content-Type: application/json" -d '{
            "text": "PROD: Salesforce deployment to Production org has completed: DEPLOYMENT SUCCESSFUL. Job Status: ${{ job.status }}",
            "themeColor": "0ed700"
            }' $TEAMS_NOTIFICATIONS_WEBHOOK
          else
            curl -X POST -H "Content-Type: application/json" -d '{
              "text": "PROD: Salesforce deployment to Production org has completed: DEPLOYMENT FAILED. Job Status: ${{ job.status }}",
              "themeColor": "FF0000"
            }' $TEAMS_NOTIFICATIONS_WEBHOOK
          fi
