@Library('dot-shared-lib@v3.3.2') _
pipeline {

    options {
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '15'))
        timeout(time: 2, unit: 'HOURS')
        timestamps()
    }

    environment {
        PROJECT_NAME = 'T1224-OneOPS'
        PROJECT_TEAM = 'myteam'
        REGISTRY = 'registry.app.corpintra.net'
        SERVER_KEY_FILE = credentials('SF_SERVER_KEY')
        CI_USER_SIT = credentials('CI_USER_SIT_SB')
        CLIENTID_SIT = credentials('CLIENTID_SIT_SB')
        URL_SIT = credentials('URL_SIT')
        API_VERSION = credentials('API_VERSION')
        SFDX_DISABLE_DNS_CHECK = true 
    }

    agent any

    stages {
        stage('Set Up Environment') {
            steps {
                setEnv(enableStatistics: false)
            }
        }
        stage ('SIT Deployment') {
            agent {
                docker {
                alwaysPull true
                image 'registry.app.corpintra.net/dmo/docker-salesforce:7.198.7'
                args '-u root'
                reuseNode true
                }
            }
            steps {
                    sh "chmod +x .deployment/scripts/*.sh && chmod +x .deployment/scripts/orchastration_mb/*.sh"
                    sh ".deployment/scripts/configSetAPIVersion.sh $API_VERSION"
                    sh ".deployment/scripts/authentication.sh $CLIENTID_SIT $CI_USER_SIT FS_SIT $SERVER_KEY_FILE $URL_SIT"
                    sh ".deployment/scripts/orchastration_mb/deploy-dir-structure.sh FS_SIT RunLocalTests"
            }
        }
    }

    post {
        always {
            cleanWs()
            dir("${env.WORKSPACE}@tmp") {
                deleteDir()
            }
        }
    }
}