name: 'CD: Deploy to PREPROD' 

on:
  workflow_dispatch:

env:
  SFDX_DISABLE_DNS_CHECK: true
  ORG_ALIAS: "MBM_PREPROD_CI"
  SALESFORCE_CLI_VERSION: ${{ vars.SALESFORCE_CLI_VERSION }}
  PREPROD_ORG: ${{ vars.PREPROD_ORG }}
  DEPLOYMENT_STYLE: ${{ vars.PREPROD_DEPLOYMENT_STYLE }}
  TARGET_ORG_TYPE: ${{ vars.PREPROD_TARGET_ORG_TYPE }}
  DEPLOY_OO_FOLDERS: ${{ vars.PREPROD_DEPLOY_OO_FOLDERS }}
  DEPLOY_OH_FOLDERS: ${{ vars.PREPROD_DEPLOY_OH_FOLDERS }}
  DEPLOY_CMP_FOLDERS: ${{ vars.PREPROD_DEPLOY_CMP_FOLDERS }}
  TESTRUN_ON_DEPLOYMENT: ${{ vars.PREPROD_TESTRUN_ON_DEPLOYMENT }}

jobs:
  deployToPREPROD:
    name: "Deploy to PREPROD"
    runs-on: [self-hosted, aks-gha-runners]
    environment: PREPROD

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install Salesforce CLI
      - name: 'Install Salesforce CLI'
        run: |
          sudo npm install --global @salesforce/cli@$SALESFORCE_CLI_VERSION --ignore-scripts
          sf --version
          if [ $DEPLOYMENT_STYLE == 'delta' ]; then
            echo 'y' | sf plugins install sfdx-git-delta
          fi

      # Make scripts executable
      - name: Make scripts executable
        run: chmod +x .deployment/scripts/*.sh && chmod +x .deployment/scripts/orchastration_mb/*.sh

      # Store secret for PREPROD
      - name: Populate auth file with PREPROD_SFDX_URL secret
        run: |
          if [ $PREPROD_ORG == 'PREPRODXC' ]; then
            echo ${{ secrets.PREPRODXC_SFDX_URL}} > ./PREPROD_SFDX_URL.txt
          else
            echo ${{ secrets.PREPROD_SFDX_URL}} > ./PREPROD_SFDX_URL.txt
          fi
      
      # Authenticate to PREPROD
      - name: Authenticate to PREPROD
        run: .deployment/scripts/authenticationSFDXURL.sh $ORG_ALIAS PREPROD_SFDX_URL.txt SetDefault

      # Deploy to PREPROD
      - name: Deploy to PREPROD
        run: |
          if [ $DEPLOYMENT_STYLE == 'delta' ]; then
            mkdir ./temp-delta-deployment
            sf sgd source delta --from $(git describe --abbrev=0) --to "HEAD" --output-dir ./temp-delta-deployment --generate-delta --ignore-file .sgdeltaignore
            ls -R -l ./temp-delta-deployment
            .deployment/scripts/deploySourceFormat.sh $ORG_ALIAS $TESTRUN_ON_DEPLOYMENT sourcepath ./temp-delta-deployment
          else
            .deployment/scripts/orchastration_mb/deploy-dir-structure.sh $ORG_ALIAS $TARGET_ORG_TYPE $DEPLOY_OO_FOLDERS $DEPLOY_OH_FOLDERS $DEPLOY_CMP_FOLDERS
          fi
