name: 'CD: STAGE - Deployment' 

on:
  push:
   branches: [ "stage" ]

env:
  INSTALLATIONKEY: ${{ secrets.INSTALLATIONKEY }}
  SFDX_DISABLE_DNS_CHECK: true 
  SALESFORCE_CLI_VERSION: ${{ vars.SALESFORCE_CLI_VERSION }}
  FROM_BRANCH: ${{ vars.FROM_BRANCH }}
  TO_BRANCH: ${{ vars.TO_BRANCH }}

jobs:
  deployToSTAGE:
    runs-on: [self-hosted, aks-gha-runners]
    environment: STAGE

    steps:
      - uses: actions/checkout@v3

      # Install Salesforce CLI
      - name: 'Install Salesforce CLI'
        run: sudo npm install --global @salesforce/cli@${SALESFORCE_CLI_V2_VERSION} --ignore-scripts

      # Store secret for STAGE
      - name: Populate auth file with STAGE_SFDX_URL secret
        run: echo ${{ secrets.STAGE_SFDX_URL}} > ./STAGE_SFDX_URL.txt

      # Make scripts executable
      - name: Make scripts executable
        run: chmod +x .deployment/scripts/*.sh && chmod +x .deployment/scripts/orchastration_mb/*.sh
      
      # Authenticate to STAGE
      - name: Authenticate to STAGE
        run: .deployment/scripts/authenticationSFDXURL.sh FS_STAGE STAGE_SFDX_URL.txt SetDefault
      
      # Deploy to STAGE
      - name: Deploy to STAGE
        run: .deployment/scripts/orchastration_mb/deploy-dir-structure.sh FS_STAGE RunLocalTests
         # .deployment/scripts/orchastration_mb/post-deployment_STAGE.sh FS_STAGE RunLocalTests - avoid overriting of quicklinks for the moment

      