name: 'CI: devINT - Deployment'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # Every day at 02:00 am

env:
  SFDX_DISABLE_DNS_CHECK: true 
  ORG_ALIAS: "devINT"
  SALESFORCE_CLI_VERSION: ${{ vars.SALESFORCE_CLI_VERSION }}
  TEAMS_NOTIFICATIONS_WEBHOOK: ${{ secrets.TEAMS_NOTIFICATIONS_WEBHOOK }}
  TESTRUN_ON_DEPLOYMENT: ${{ vars.DEVINT_TESTRUN_ON_DEPLOYMENT }}
  TARGET_ORG_TYPE: "DEVOPSSANDBOX"
  DEPLOY_OO_FOLDERS: "TRUE"
  DEPLOY_OH_FOLDERS: "TRUE"
  DEPLOY_CMP_FOLDERS: "TRUE"
  

jobs:
  deployToDevINT:
    name: Deploy to devINT
    runs-on: [self-hosted, aks-gha-runners]
    environment: devINT

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install Salesforce CLI
      - name: 'Install Salesforce CLI'
        run: |
          sudo npm install --global @salesforce/cli@$SALESFORCE_CLI_VERSION --ignore-scripts
          sf --version
          
      # Make scripts executable
      - name: Make scripts executable
        run: chmod +x .deployment/scripts/*.sh && chmod +x .deployment/scripts/orchastration_mb/*.sh

      # Handle irrelevant metadata against devINT org
      - name: Handle irrelevant metadata
        run: .deployment/scripts/orchastration_mb/pre-irrelevantMetadata_SIT.sh deployment

      # Store secret for devINT
      - name: Populate auth file with DEVINT_SFDX_URL secret
        run: echo ${{ secrets.DEVINT_SFDX_URL }} > ./DEVINT_SFDX_URL.txt

      # Authenticate to devINT
      - name: Authenticate to devINT
        run: .deployment/scripts/authenticationSFDXURL.sh $ORG_ALIAS DEVINT_SFDX_URL.txt SetDefault

      # Deploy to devINT
      - name: Deploy to devINT
        run: |
          .deployment/scripts/orchastration_mb/deploy-dir-structure.sh $ORG_ALIAS $TARGET_ORG_TYPE $DEPLOY_OO_FOLDERS $DEPLOY_OH_FOLDERS $DEPLOY_CMP_FOLDERS
          .deployment/scripts/deploySourceFormat.sh $ORG_ALIAS $TESTRUN_ON_DEPLOYMENT sourcepath fs_post_org-dependent/SIT
