name: 'CI: PreProd - Validation' 

on:
  workflow_dispatch:
  push:
   branches: [ "release/*" ]

env:
  SFDX_DISABLE_DNS_CHECK: true 
  ORG_ALIAS: "MBM_PREPROD_CI"
  SALESFORCE_CLI_VERSION: ${{ vars.SALESFORCE_CLI_VERSION }}
  PREPROD_ORG: ${{ vars.PREPROD_ORG }}

jobs:
  validateAgainstPreProd:
    name: "Validate against PreProd"
    runs-on: [self-hosted, aks-gha-runners]
    environment: PREPROD
    continue-on-error: true

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install Salesforce CLI
      - name: 'Install Salesforce CLI'
        run: |
          sudo npm install --global @salesforce/cli@$SALESFORCE_CLI_VERSION --ignore-scripts
          sf --version
          echo 'y' | sf plugins install sfdx-git-delta

      # Store secret for PREPROD
      - name: Populate auth file with PREPROD_SFDX_URL secret
        run: |
          if [ $PREPROD_ORG == 'PREPRODXC' ]; then
            echo ${{ secrets.PREPRODXC_SFDX_URL}} > ./PREPROD_SFDX_URL.txt
          else
            echo ${{ secrets.PREPROD_SFDX_URL}} > ./PREPROD_SFDX_URL.txt
          fi

      # Make scripts executable
      - name: Make scripts executable
        run: chmod +x .deployment/scripts/*.sh

      # Authenticate to PREPROD
      - name: Authenticate to PREPROD
        run: .deployment/scripts/authenticationSFDXURL.sh $ORG_ALIAS PREPROD_SFDX_URL.txt SetDefault

      # Remove obsolete metadata to PREPROD
      - name: Remove obsolete metadata to PREPROD
        run: |
          rm -rf fs_post_org-dependent/OHqa
          rm -rf fs_post_org-dependent/SIT
          rm -rf fs_post_org-dependent/STAGE
          rm -rf fs_post_org-dependent/PROD/labels/CustomLabels.labels-meta.xml
      
      # Validate against PREPROD
      - name: Validate against PREPROD
        run: |
          mkdir ./temp-delta-deployment
          sf sgd source delta --from $(git describe --abbrev=0) --to "HEAD" --output-dir ./temp-delta-deployment --generate-delta --ignore-file .sgdeltaignore
          ls -R -l ./temp-delta-deployment
          .deployment/scripts/validateSourceFormat.sh $ORG_ALIAS RunLocalTests sourcepath ./temp-delta-deployment

  validateAgainstProd:
    name: "Validate against PROD"
    runs-on: [self-hosted, aks-gha-runners]
    needs: validateAgainstPreProd
    environment: PROD

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install Salesforce CLI
      - name: 'Install Salesforce CLI'
        run: |
          sudo npm install --global @salesforce/cli@$SALESFORCE_CLI_VERSION --ignore-scripts
          sf --version
          echo 'y' | sf plugins install sfdx-git-delta

      # Store secret for PROD
      - name: Populate auth file with PROD_SFDX_URL secret
        run: echo ${{ secrets.DEVHUB_SFDX_URL}} > ./PROD_SFDX_URL.txt

      # Make scripts executable
      - name: Make scripts executable
        run: chmod +x .deployment/scripts/*.sh

      # Authenticate to PROD
      - name: Authenticate to PROD
        run: .deployment/scripts/authenticationSFDXURL.sh MBM_PROD_CI PROD_SFDX_URL.txt SetDefault
      
      # Validate against PROD
      - name: Validate against PROD
        run: |
          mkdir ./temp-delta-deployment
          sf sgd source delta --from $(git describe --abbrev=0) --to "HEAD" --output-dir ./temp-delta-deployment --generate-delta --ignore-file .sgdeltaignore
          ls -R -l ./temp-delta-deployment
          .deployment/scripts/validateSourceFormat.sh MBM_PROD_CI RunLocalTests sourcepath ./temp-delta-deployment