name: 'CI: STAGE - Validation' 

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *' # Every Day at 01:00 am - changed from merge on develop due to often too many PRs getting merged

env:
  SFDX_DISABLE_DNS_CHECK: true 
  ORG_ALIAS: "MBM_UAT_CI"
  SALESFORCE_CLI_VERSION: ${{ vars.SALESFORCE_CLI_VERSION }}
  TESTRUN_ON_VALIDATION: "RunLocalTests"

jobs:
  validateAgainstSTAGE:
    name: Validate against STAGE
    runs-on: [self-hosted, aks-gha-runners]
    environment: STAGE

    steps:
      - uses: actions/checkout@v3

      - id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install Salesforce CLI
      - name: 'Install Salesforce CLI'
        run: |
          sudo npm install --global @salesforce/cli@$SALESFORCE_CLI_VERSION --ignore-scripts
          sf --version

      # Store secret for STAGE
      - name: Populate auth file with STAGE_SFDX_URL secret
        run: echo ${{ secrets.STAGE_SFDX_URL}} > ./STAGE_SFDX_URL.txt

      # Make scripts executable
      - name: Make scripts executable
        run: chmod +x .deployment/scripts/*.sh

      # Authenticate to STAGE
      - name: Authenticate to STAGE
        run: .deployment/scripts/authenticationSFDXURL.sh $ORG_ALIAS STAGE_SFDX_URL.txt SetDefault

      # Temp remove omni components
      - name: Remove omni related metadata
        run: .deployment/scripts/orchastration_mb/pre-irrelevantMetadata_STAGE.sh validation

      # Validate package directories
      - name: Validate package directories against STAGE
        run: |
          echo "--- Validating package directories from sfdx-project.json ---"
          .deployment/scripts/validateSourceFormat.sh $ORG_ALIAS $TESTRUN_ON_VALIDATION sourcepath ./
