name: 'CI: SIT - Scheduled full deploy'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0' # Every Sunday at 02:00 am

env:
  SFDX_DISABLE_DNS_CHECK: true 
  ORG_ALIAS: "MBM_SIT_CI"
  SALESFORCE_CLI_VERSION: ${{ vars.SALESFORCE_CLI_VERSION }}
  TESTRUN_ON_DEPLOYMENT: ${{ vars.SIT_TESTRUN_ON_DEPLOYMENT }}
  TARGET_ORG_TYPE: "DEVOPSSANDBOX"
  DEPLOY_PRIMARY_SOURCE: "TRUE"
  DEPLOY_SECONDARY_SOURCE: "TRUE"
  DEPLOY_OPTIONAL_SOURCE: "TRUE"

jobs:
  deployToSIT:
    name: "CI: Deploy to SIT"
    runs-on: [self-hosted, aks-gha-runners]
    environment: SIT

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install Salesforce CLI & sfdx-git-delta Plugin if needed 
      - name: 'Install Salesforce CLI'
        run: |
          sudo npm install --global @salesforce/cli@$SALESFORCE_CLI_VERSION --ignore-scripts
          sf --version
          
      # Make scripts executable
      - name: Make scripts executable
        run: chmod +x .deployment/scripts/*.sh && chmod +x .deployment/scripts/orchastration_mb/*.sh

      # Handle irrelevant metadata against SIT org
      - name: Handle irrelevant metadata
        run: .deployment/scripts/orchastration_mb/pre-irrelevantMetadata_SIT.sh deployment
      
      # Store secret for SIT
      - name: Populate auth file with SIT_SFDX_URL secret
        run: echo ${{ secrets.SIT_SFDX_URL}} > ./SIT_SFDX_URL.txt
      
      # Authenticate to SIT
      - name: Authenticate to SIT
        run: .deployment/scripts/authenticationSFDXURL.sh $ORG_ALIAS SIT_SFDX_URL.txt SetDefault

      # Deploy to SIT
      - name: Deploy to SIT
        run: | 
          .deployment/scripts/orchastration_mb/deploy-dir-structure.sh $ORG_ALIAS $TARGET_ORG_TYPE $DEPLOY_PRIMARY_SOURCE $DEPLOY_SECONDARY_SOURCE $DEPLOY_OPTIONAL_SOURCE
          if [ -d "fs_post_org-dependent/SIT" ]; then
            .deployment/scripts/deploySourceFormat.sh $ORG_ALIAS $TESTRUN_ON_DEPLOYMENT sourcepath fs_post_org-dependent/SIT
          fi
          